dist: xenial
sudo: false

env:
  - ZOLA_URL=https://github.com/ousttrue/zola/releases/download/v0.13.0.a/zola.xz

before_script:
  - wget ${ZOLA_URL}
  - xz -d `basename ${ZOLA_URL}`
  - chmod +x zola
  - sudo mv zola /usr/local/bin/zola

script:
  - zola build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  target_branch: master
  local_dir: public
  on:
    branch: zola
