# The URL the site will be built for
base_url = "https://ousttrue.github.io/"

title = "三次元日誌"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    {name = "tags", rss = false},
]

# custom
orphan_as_transparent = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

[[extra.books]]
label = "cmake_book"
url = "https://ousttrue.github.io/cmake_book/"
taxonomies.tags = ["cmake"]

[[extra.books]]
label = "rust練習帳"
url = "https://ousttrue.github.io/rust_exercise_book/"
taxonomies.tags = ["rust"]

[[extra.books]]
label = "vimメモ"
url = "https://ousttrue.github.io/vim_memo/"
taxonomies.tags = ["nvim"]

