baseURL = "https://ousttrue.github.io/"
languageCode = "ja"
title = "三次元日誌"
pluralizeListTitles = false
# preserveTaxonomyNames = true
theme = "practice"
enableGitInfo = true

[taxonomies]
tag = "tags"
